### ISSUE TITLE
如何导入外部物理空间

### ISSUE THREAD

**Issue by sugarmantybb** [omegafantasy/OpenRDW2#1]
请问一下如果我想导入外部的物理空间，比如其他unity项目的环境，应该如何操作

**Comment by omegafantasy** [comment]
首先确认一下是否想导入的是**物理**空间，也就是用户真实所处的空间。
如果想导入虚拟空间，可以考虑将场景整体放在编辑器层级树里`Virtual World`下面。
OpenRDW2（及OpenRDW）设置物理空间一般是通过直接选择Tracking Space的类型，或是外部导入txt文件指定每个边界点和中间的障碍物，之后程序会自动生成可视化效果。由于物理空间在VR体验中完全不可见，其意义可能仅限于可视化展示或是监测，所以我们暂时没有考虑过适配或者导入一个“更好”的物理空间。
如果目前有导入需求的话可能需要修改代码，比如设置运行时加载场景。

**Comment by sugarmantybb** [comment]
好的！多谢回答。想导入的的确是物理空间，这样看来的确是需要修改代码
